[project]
name = 'nakademo'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.pox-4]
path = 'contracts/pox-4.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
